# Generated by Django 5.0 on 2023-12-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='manages',
            field=models.ManyToManyField(related_name='managed_by', to='database.account', verbose_name='управляет'),
        ),
    ]
